### ISSUE TITLE
flatlatex workaround to keep spaces

### ISSUE THREAD

**Issue by jb-leger** [ppizarror/PyDetex#23]
Hi,

I am the dev of [`flatlatex`](https://pypi.org/project/flatlatex/). I do not understand when exactly you use `flatlatex` (but I am happy to see my module is useful), but I found one thing which can be a misuse. In [`_utils_tex.py` line 785][L785] you replace spaces by a special substring, and you do the reverse after conversion [line 790][L790]. I think this because you want to preserve spaces.

In fact, this is a very bad idea, because, for example in LaTeX, this `\frac a2` is pefectly valid, and give normaly ᵃ⁄₂, and this works fine with `flatlatex`. But if you replace space, the parsing get you a incorrect solution.

I had the same problem, and sometime I want to keep space. Therefore I had some unpushed code for that, I commit the code and I pushed it and I added a option `keep_space` in [flatlatex v0.14][v0.14] (but I set the default to `False` to preserve backward compat) (I pushed the doc in docstring in [v0.15]).

[L785]: https://github.com/ppizarror/PyDetex/blob/master/pydetex/_utils_tex.py#L785
[L790]: https://github.com/ppizarror/PyDetex/blob/master/pydetex/_utils_tex.py#L790
[v0.14]: https://github.com/jb-leger/flatlatex/tree/v0.14
[v0.15]: https://github.com/jb-leger/flatlatex/tree/v0.15

**Comment by ppizarror** [comment]
Hello, thanks for your library! I've updated the module requirements. Greetings 😄
