### ISSUE TITLE
Support acronym package

### ISSUE THREAD

**Issue by MariusLutz** [ppizarror/PyDetex#38]
**Is your feature request related to a problem? Please describe.**
This is a feature request to support the acronym package. Acronyms typeset as \ac{XYZ} are removed, changing the context and grammar of the text.

**Describe the solution you'd like**
Replace \ac{} with plain text within the brackets.

**Comment by ppizarror** [comment]
Can you test #39?

**Comment by MariusLutz** [comment]
Works as expected. May I also suggest to include the related commands `\acs, \acl` and `\acf`?

**Comment by ppizarror** [comment]
These command outputs are the same as ``\ac``?

**Comment by MariusLutz** [comment]
Yes, at least in the context of PyDetex
