### ISSUE TITLE
Setup with pipx

### ISSUE THREAD

**Issue by klieret** [ppizarror/PyDetex#41]
**Is your feature request related to a problem? Please describe.**

This is a standalone tool, so I would like to install it in a separate virtual environment. This is cumbersome.

**Describe the solution you'd like**

[`pipx`](https://pypa.github.io/pipx/) is the standard tool for this use case. This will not require any additional work on your side but to specify the `entry_points` in `setup.py`, see [here](https://pypa.github.io/pipx/how-pipx-works/). Then, users can simply run `pipx run pydetex`, and `pipx` will download, install, and run `pydetex` 🎉 

**Additional context**

Thanks a lot for developing this package, very useful!

**Comment by ppizarror** [comment]
Hi! I've added pipx support in the new v1.0.8. It works great

**Comment by klieret** [comment]
Ah, turns out this was my bad, I got

```
pipx run pydetex --spec pydetex                                                                                                                                                                                                      ─╯
'pydetex' executable script not found in package 'pydetex'.
Available executable scripts:
```

but actually I seem to have been stuck with an old version of `pipx`. Upgrading `pipx` solved the issue for me :) 

Thanks!
