### ISSUE TITLE
Pyperclip not recognized.

### ISSUE THREAD

**Issue by pauloney** [ppizarror/PyDetex#43]
- OS: Ubuntu 22.04
- python version: v3.9.10
- pydetex version: v1.0.8

Running the command from a shell, I get:

````
$ python3 -m pydetex.gui
/usr/local/lib/python3.8/dist-packages/pydetex/gui.py:246: UserWarning: pyperclip is not available on your system (copy/paste mechanism). GUI buttons were disabled
  warn(error)
````

Even though pyperclip seems to be installed fine, and Copy & Paste inside the GUI works fine.

````
$ locate pyperclip
/usr/lib/python3/dist-packages/prompt_toolkit/clipboard/pyperclip.py
````

Indeed the two buttons at the bottom of the window are disabled.

If I execute:

````
python3 -m pip show pyperclip 
````

It recognizes `pyperclip` as installed, no problems.

**Comment by ppizarror** [comment]
Hi, I guess that Pydetex cannot import the library. If you look at the path, python3 relies on lib/python3.8/dist-packages/... whereas paperclip is on lib/python3/dist-packages. This error happens while trying to execute pyperclip.paste()

https://github.com/ppizarror/PyDetex/blob/3b93bc938f8c426d10b39559019b8bdeecd93527/pydetex/gui.py#L239-L248

**Comment by ppizarror** [comment]
Hi, I have updated the tool. Now it creates a much more complete warn message if pyperclip fails. See updated v1.1.0. I am closing this issue.

https://github.com/ppizarror/PyDetex/blob/42ddea2f0b587334f818d909937e6bfea5ea8971/pydetex/gui.py#L252-L259
